"""add snapshot fields to calls

Revision ID: 8bb2fb977ae3
Revises: cd96f8ba036b
Create Date: 2025-12-30 01:37:19.185448

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8bb2fb977ae3'
down_revision = 'cd96f8ba036b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calls', sa.Column('pair_address', sa.String(length=128), nullable=True))
    op.add_column('calls', sa.Column('dex_id', sa.String(length=64), nullable=True))
    op.add_column('calls', sa.Column('pair_created_at_ms', sa.BigInteger(), nullable=True))
    op.add_column('calls', sa.Column('liquidity_usd', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('fdv', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('market_cap', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('vol_m5', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('vol_h1', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('vol_h6', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('vol_h24', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('pc_m5', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('pc_h1', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('pc_h6', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('pc_h24', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('buys_m5', sa.Integer(), nullable=True))
    op.add_column('calls', sa.Column('sells_m5', sa.Integer(), nullable=True))
    op.add_column('calls', sa.Column('buys_h1', sa.Integer(), nullable=True))
    op.add_column('calls', sa.Column('sells_h1', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'sells_h1')
    op.drop_column('calls', 'buys_h1')
    op.drop_column('calls', 'sells_m5')
    op.drop_column('calls', 'buys_m5')
    op.drop_column('calls', 'pc_h24')
    op.drop_column('calls', 'pc_h6')
    op.drop_column('calls', 'pc_h1')
    op.drop_column('calls', 'pc_m5')
    op.drop_column('calls', 'vol_h24')
    op.drop_column('calls', 'vol_h6')
    op.drop_column('calls', 'vol_h1')
    op.drop_column('calls', 'vol_m5')
    op.drop_column('calls', 'market_cap')
    op.drop_column('calls', 'fdv')
    op.drop_column('calls', 'liquidity_usd')
    op.drop_column('calls', 'pair_created_at_ms')
    op.drop_column('calls', 'dex_id')
    op.drop_column('calls', 'pair_address')
    op.drop_column('calls', 'snapshot_at')
    # ### end Alembic commands ###
