"""init

Revision ID: 93c7064ac543
Revises: 
Create Date: 2025-12-28 00:15:25.730891

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '93c7064ac543'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('telegram_username', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('live_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_key'), 'channels', ['key'], unique=True)
    op.create_index(op.f('ix_channels_telegram_username'), 'channels', ['telegram_username'], unique=True)
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('entry_price_usd', sa.Float(), nullable=True),
    sa.Column('ignore_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'mint', name='uq_calls_channel_mint')
    )
    op.create_index(op.f('ix_calls_channel_id'), 'calls', ['channel_id'], unique=False)
    op.create_index(op.f('ix_calls_mint'), 'calls', ['mint'], unique=False)
    op.create_table('price_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('t_sec', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 't_sec', name='uq_price_points_call_tsec')
    )
    op.create_index(op.f('ix_price_points_call_id'), 'price_points', ['call_id'], unique=False)
    op.create_index(op.f('ix_price_points_t_sec'), 'price_points', ['t_sec'], unique=False)
    op.create_table('strategy_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('strategy_key', sa.String(length=64), nullable=False),
    sa.Column('tp_pct', sa.Float(), nullable=False),
    sa.Column('sl_pct', sa.Float(), nullable=False),
    sa.Column('entry_price_usd', sa.Float(), nullable=False),
    sa.Column('exit_price_usd', sa.Float(), nullable=False),
    sa.Column('exit_t_sec', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'strategy_key', name='uq_strategy_results_call_strategy')
    )
    op.create_index(op.f('ix_strategy_results_call_id'), 'strategy_results', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_results_call_id'), table_name='strategy_results')
    op.drop_table('strategy_results')
    op.drop_index(op.f('ix_price_points_t_sec'), table_name='price_points')
    op.drop_index(op.f('ix_price_points_call_id'), table_name='price_points')
    op.drop_table('price_points')
    op.drop_index(op.f('ix_calls_mint'), table_name='calls')
    op.drop_index(op.f('ix_calls_channel_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_channels_telegram_username'), table_name='channels')
    op.drop_index(op.f('ix_channels_key'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
