"""call snapshot fields

Revision ID: cd96f8ba036b
Revises: 93c7064ac543
Create Date: 2025-12-28 08:50:25.047584

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'cd96f8ba036b'
down_revision = '93c7064ac543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
